#!/bin/zsh

site=$(pwd)
dirname='contact'
svelte="svelte/${dirname}"

# build hugo site
rm -rf public
hugo --minify

cd $svelte
./pull $dirname
npm run build
cd $site

#copy svelte build bundle and index
cp -r "${svelte}/public/" "public/${dirname}"

#dockerize
./dockerize
