#!/bin/zsh

site=$(pwd)
dirnames=('contact' 'reviews')

# build hugo site
rm -rf public
hugo --minify

for dirname in $dirnames
do
  svelte="svelte/${dirname}"
  cd $svelte
  ./pull $dirname
  npm run build
  cd $site

  #copy svelte build bundle and index
  cp -r "${svelte}/public/" "public/${dirname}"
done

#dockerize
./dockerize
