baseURL = "https://mobilewelding.llc/"
languageCode = "en-us"
theme = "mobilewelding"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-220403400-1"
[params]
  name = "Mobile Welding LLC"
  author = "Presence Web Services LLC"
  description = "Mobile Welding LLC offers mobile and portable metal welding, cutting, repair, and fabrication services."
