baseURL = "https://mobilewelding.llc"
languageCode = "en-us"
title = "Home"
theme = "mobilewelding"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  author = "Presence Web Services"
  description = ""
