baseURL = "https://presencewebservices.net/"
languageCode = "en-us"
title = "Home"
theme = "presence"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  author = "Presence Web Services"
  description = "Cultivate your online presence. We offer custom website creation services. Contact us today!"
