baseURL = "https://presencewebservices.net"
languageCode = "en-us"
title = "Home"
theme = "presence"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  author = "Presence Web Services"
  description = "Establish your online presence. We offer custom website design and creation services. Contact us today!"
